apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubespring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubespring-app
  template:
    metadata:
      labels:
        app: kubespring-app
    spec:
      nodeSelector:
        isdeploy: deploy
      containers:
        - name: springboot
          image: vajgi90/kubespring

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /ride
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /ride
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /ride
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kubespring-app-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kubespring-app
